### ISSUE TITLE
How can I gain access to SlidingView

### ISSUE THREAD

**Issue by jMelvins** [hoomazoid/CTSlidingUpPanel#1]
I need to change tableView.isScrollEnabled from one of the functions like didPanelCollapse(). So How can I do this? When I try to use delegate tableView in SlideController is nil.

**Comment by andriadze** [comment]
Hi, sorry for the late response. 
Can you provide some code of what(and how) you are trying to achieve?

**Comment by jMelvins** [comment]
I wrote delegate for my VC like this: 

```
protocol MapViewControllerDelegate {
    func isTableViewScrollEnabled(enabled: Bool)
}
```

When I setup SlidingView I appoint this like delegate for my vc:

        bottomController = CTBottomSlideController(parent: view, bottomView: bottomView, tabController: self.tabBarController, navController: self.navigationController, visibleHeight: 132)
        bottomController?.setAnchorPoint(anchor: 0.43)
        bottomController?.delegate = self
        let vc = storyboard?.instantiateViewController(withIdentifier: "BottomSheetViewController") as! BottomSheetViewController
        delegate = vc

In CTBottomSlideDelegate extension I try to perform delegate method: 
```
func didPanelCollapse() {
        print("Collapsed")
        delegate?.isTableViewScrollEnabled(enabled: true)
    }
```
and finally in BottomSheetViewController class I get this:
![2017-10-27 2 36 44](https://user-images.githubusercontent.com/24705601/32102377-af32fe7e-bb24-11e7-90bd-d47be1d21f68.png)

**Comment by andriadze** [comment]
Hi, I don't think this is a problem with a library.

From what I got, I think what you are doing is instantiating **BottomSheetViewController** twice.

**First time when original view loads** and then: 
`let vc = storyboard?.instantiateViewController(withIdentifier: "BottomSheetViewController") as! BottomSheetViewController 
`
- this creates second ViewController 
- when panel collapses it calls second view controllers method(Not the original ones).  
- Since this second viewcontroller is not loaded(It is only instantiated) its tableview is nil.

Maybe I'm not getting everything correctly, but I think that this is the issue. I think what you should be doing is  `delegate = self` instead of  `delegate = vc`

**Comment by jMelvins** [comment]
Thank you for answer! you're right, when I try to:
`let vc = storyboard?.instantiateViewController(withIdentifier: "BottomSheetViewController") as! BottomSheetViewController`
I create a new VC. My mistake, I'm sorry for this. But It's not clearly understandable how to turn to BottomSheetVC from ParrentVC to appoint its as delegate

**Comment by andriadze** [comment]
hmm I think if you do 
`delegate = self ` instead of `delegate = vc`

in `viewDidLoad()` or something it will work

**Comment by jMelvins** [comment]
I'm sorry for my silence. 
I didn't actually understand how can I get access for BottomSheetVC from MapVC. Can you explain this? Thank you!

**Comment by andriadze** [comment]
Hmm, it is hard for me to judge what you are trying to do as I don't know what your project setup is. 
Sorry, but your question, as of now, is not related to this library. It is specific only to your project setup and how you organized your code. 

I think you should head over to StackOverflow.com and ask your question there.
While creating your question on stackoverflow try to be as descriptive as possible. Provide as much code as you can.
