### ISSUE TITLE
iPhone X Support

### ISSUE THREAD

**Issue by DeluxeAlonso** [hoomazoid/CTSlidingUpPanel#4]
Hi there, is there a way we can make the bottom view slide up from the safe area of the view and not from the bottom of it? I've tried to setting up the bottom constraint of the bottom view but this is not recommended on the readme.

**Comment by andriadze** [comment]
oh, I completely forgot iPhone X. Will make sure to update the lib.

**Comment by andriadze** [comment]
So, I was thinking what would be the best way of fixing this issue. Problem is that sliding view is located below screen. 

So i think best option to fix this would be to wrap sliding view in another view. That upper view will have bottom constraint and it will be possible to position that parent view anywhere.

Will look into this further and issue an update in 1-2 days

**Comment by andriadze** [comment]
Okay I got around the issue Update won't be necessary.

Here's how it works:
Suppose You have a Sliding View(That's the view you provide to Sliding Controller)
1. Now take that view and wrap it in a generic UIView.
2. Enable Clips to bounds for parent view(this is necessary)
3. Set any constraints you want for the parent view.
4. Now while initializing SlidingController in parent property provide the wrapper view instead of root view.

Done!

![screen shot 2018-01-14 at 2 57 55 pm](https://user-images.githubusercontent.com/15636628/34915222-b079fab2-f93b-11e7-8c3b-f926f41afe6c.png)

**Comment by DeluxeAlonso** [comment]
Hi @hoomazoid, it works! Thanks a lot for your time buddy.

**Comment by andriadze** [comment]
Glad to help!
